services:
  # --- INFRASTRUCTURE ---
  keycloak:
    build: ./keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: keycloak
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  imgproxy:
    image: darthsim/imgproxy:latest
    ports:
      - "8081:8080"
    environment:
      - IMGPROXY_ENABLE_WEBP_DETECTION=true

  # --- APPLICATIONS JAVA ---
  profiles-api:
    build: ./profiles-api
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker, security
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/one-citations
    depends_on:
      - mongo
      - keycloak

  citations-api:
    build: ./citations-api
    ports:
      - "9091:9091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/one-citations
    depends_on:
      - mongo
      - profiles-api

  images-api:
    build: ./images-api
    ports:
      - "9092:9092"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/one-citations
    depends_on:
      - mongo
      - imgproxy

  # --- OUTILS ---
  swagger:
    image: swaggerapi/swagger-ui
    ports: 
      - "8888:8080"
    environment:
      URLS: "[ { url: 'http://localhost:9091/v3/api-docs', name: 'Citations' }, { url: 'http://localhost:9090/v3/api-docs', name: 'Profiles' }, { url: 'http://localhost:9092/v3/api-docs', name: 'Images' } ]"
      DEEP_LINKING: "true"
    volumes:
      - ./swagger:/doc

  kong:
    image: kong:3.1.1-alpine
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    volumes:
      - ./kong/conf:/usr/local/kong/declarative
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - profiles-api
      - citations-api
      - images-api
      - keycloak

volumes:
  mongo_data: