spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/one-citations-profile
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/one-citations