spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/one-citations-profile
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/one-citations/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger
      use-pkce-with-authorization-code-grant: true