spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/one-citations-citations
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/one-citations

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger
      use-pkce-with-authorization-code-grant: true