spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: citations-db
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/one-citations/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger
      use-pkce-with-authorization-code-grant: true