server:
  port: 9091

spring:
  application:
    name: citations-api
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/citations 

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/one-citations